name: Ocaml CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ocaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.0

      - name: Install dependencies
        run: opam install -y ounit2 ocamlformat containers containers-data qcheck


      - name: Build and Run tests
        run: |
          opam exec -- dune build
          opam exec -- dune runtest

        env:
          CI: true

  lint-opam:
    permissions:
      attestations: write
      contents: read
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Lint
        run: opam install zanuda.1.0.0 -y